'use client';

import { useState } from 'react';
import { usePrivy } from '@privy-io/react-auth';
import { useWalrus, ZKProof } from '@/lib/walrus';

export default function ZKProofManager() {
  const { user, authenticated } = usePrivy();
  const { walrusService } = useWalrus();
  const [isGenerating, setIsGenerating] = useState(false);
  const [proofId, setProofId] = useState<string | null>(null);

  const generateAndStoreProof = async () => {
    if (!authenticated || !user?.wallet?.address) {
      alert('Please connect your wallet first');
      return;
    }

    setIsGenerating(true);
    try {
      // Create a sample ZK proof
      const proof: ZKProof = {
        id: `proof_${Date.now()}`,
        proof: 'sample_proof_data', // This would be generated by Tusk
        publicInputs: ['input1', 'input2'],
        timestamp: Date.now(),
        userAddress: user.wallet.address
      };

      // Store the proof on Walrus
      const storageId = await walrusService.storeZKProof(proof);
      setProofId(storageId);
      
      console.log('Proof stored on Walrus with ID:', storageId);
    } catch (error) {
      console.error('Error generating proof:', error);
      alert('Failed to generate proof');
    } finally {
      setIsGenerating(false);
    }
  };

  const verifyProof = async () => {
    if (!proofId) return;
    
    try {
      const isValid = await walrusService.verifyZKProof({
        id: proofId,
        proof: 'sample_proof_data',
        publicInputs: [],
        timestamp: Date.now(),
        userAddress: user?.wallet?.address || ''
      });
      
      alert(isValid ? 'Proof verified successfully!' : 'Proof verification failed');
    } catch (error) {
      console.error('Error verifying proof:', error);
      alert('Failed to verify proof');
    }
  };

  if (!authenticated) {
    return (
      <div className="text-center text-gray-500">
        Please connect your wallet to generate ZK proofs
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <button
        onClick={generateAndStoreProof}
        disabled={isGenerating}
        className="w-full py-3 rounded-lg bg-black text-white font-semibold text-lg hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-black transition disabled:opacity-50"
      >
        {isGenerating ? 'Generating Proof...' : 'Generate & Store ZK Proof'}
      </button>
      
      {proofId && (
        <div className="space-y-2">
          <div className="text-sm text-gray-600">
            Proof ID: {proofId}
          </div>
          <button
            onClick={verifyProof}
            className="w-full py-2 rounded-lg border border-gray-300 text-base font-semibold bg-white hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-black transition"
          >
            Verify Proof
          </button>
        </div>
      )}
    </div>
  );
} 